name: weather_app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  chopper: ^8.0.1+1
  collection: ^1.18.0
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^11.1.0
  go_router: ^14.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  chopper_generator: ^8.0.1
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  drift_dev: ^2.19.1

flutter:
  uses-material-design: true
